# -*- coding: utf-8 -*-
"""Hate_speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111PRNmi0kPKkQ6r_0Id_pCOfDBfgod6l
"""

!pip install transformers datasets

from transformers import pipeline

# Load pre-trained zero-shot classification model
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Sample text input
text = "They should all be deported. This country is not for them."

# Candidate labels for classification
candidate_labels = ["hate speech", "offensive", "neutral", "religious hate", "gender discrimination"]

# Perform zero-shot classification
result = classifier(text, candidate_labels)

# Display the result
for label, score in zip(result["labels"], result["scores"]):
    print(f"{label}: {score:.4f}")

from datasets import load_dataset

# Load the hate speech subset from tweet_eval
dataset = load_dataset("tweet_eval", "hate", split="train[:20]")  # First 20 rows
dataset = dataset.shuffle(seed=42)

# Show sample
for i in range(3):
    print(f"\nSample {i+1}:")
    print("Text:", dataset[i]["text"])
    print("Label:", dataset[i]["label"])  # 0: non-hate, 1: hate

from transformers import pipeline
from datasets import load_dataset

# Load zero-shot model
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Load a small subset of the hate dataset
dataset = load_dataset("tweet_eval", "hate", split="train[:10]")

# Define possible labels
candidate_labels = ["hate speech", "offensive", "neutral"]

# Loop through samples and classify
for i in range(5):
    text = dataset[i]["text"]
    print(f"\n📝 Text {i+1}: {text}")

    result = classifier(text, candidate_labels)

    # Print scores
    for label, score in zip(result["labels"], result["scores"]):
        print(f"{label}: {score:.4f}")

# Load multilingual model (supports Urdu, Arabic, etc.)
multi_classifier = pipeline("zero-shot-classification", model="joeddav/xlm-roberta-large-xnli")

# Test the same sentence
text = "یہ لوگ ہمارے ملک کو خراب کر رہے ہیں۔"  # Urdu hate speech example
result = multi_classifier(text, candidate_labels)

print("\nMultilingual Classification (Urdu example):")
for label, score in zip(result["labels"], result["scores"]):
    print(f"{label}: {score:.4f}")

import matplotlib.pyplot as plt

# Use English example
text = "They should all be deported. This country is not for them."
result = classifier(text, candidate_labels)

# Plot scores
plt.figure(figsize=(8,4))
plt.bar(result['labels'], result['scores'], color='tomato')
plt.title("Zero-shot Hate Speech Detection")
plt.ylabel("Confidence Score")
plt.ylim(0, 1)
plt.grid(True)
plt.show()

